// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using client.Data;

#nullable disable

namespace backend.Migrations.Client
{
    [DbContext(typeof(ClientContext))]
    [Migration("20230811212824_atualiza")]
    partial class AtualizaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            ConfigureModelBuilder(modelBuilder);
        }

        private static void ConfigureModelBuilder(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            ConfigureClientEntity(modelBuilder);
            #pragma warning restore 612, 618
        }

        private static void ConfigureClientEntity(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Client>(b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("Cnpj")
                    .HasColumnType("int");

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("datetime2");

                b.Property<string>("NameClient")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RespClient")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TipoClient")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Client");
            });
        }
    }
}