// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using client.Data;

#nullable disable

namespace backend.Migrations.Client
{
    [DbContext(typeof(ClientContext))]
    [Migration("20230811212824_atualiza")]
    partial class AtualizaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            if (modelBuilder == null) throw new ArgumentNullException(nameof(modelBuilder));
            ConfigureModelBuilder(modelBuilder);
        }

        private static void ConfigureModelBuilder(ModelBuilder modelBuilder)
        {
            if (modelBuilder == null) throw new ArgumentNullException(nameof(modelBuilder));

            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation(ProductVersionAnnotation, ProductVersionValue)
                .HasAnnotation(RelationalMaxIdentifierLengthAnnotation, "128");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            ConfigureClientEntity(modelBuilder);
            #pragma warning restore 612, 618
        }

        private static void ConfigureClientEntity(ModelBuilder modelBuilder)
        {
            if (modelBuilder == null) throw new ArgumentNullException(nameof(modelBuilder));

            modelBuilder.Entity<Client>(b =>
            {
                b.Property<int>(IdPropertyName)
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>(IdPropertyName));

                b.Property<int>("Cnpj")
                    .HasColumnType("int");

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("datetime2");

                b.Property<string>("NameClient")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RespClient")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TipoClient")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey(IdPropertyName);

                b.ToTable("Client");
            });
        }

        // Constants for annotations and property names to avoid magic strings.
        private const string ProductVersionAnnotation = "ProductVersion";
        private const string ProductVersionValue = "7.0.10";
        private const string RelationalMaxIdentifierLengthAnnotation = "Relational:MaxIdentifierLength";
        private const string IdPropertyName = "Id";

        // NOTE: Security: Authentication (JWT/cookie) and role-based authorization
        // should be configured at the application startup (e.g., in Program.cs / Startup.cs).
        // CORS should be restricted to known origins in production. These concerns are
        // intentionally not implemented in a migration designer file; ensure they are
        // applied in the Web API configuration.
    }
}
