// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using client.Data;

#nullable disable

namespace backend.Migrations.Client
{
    [DbContext(typeof(ClientContext))]
    partial class ClientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            ConfigureModelAnnotations(modelBuilder);
            ConfigureClientEntity(modelBuilder);
        }

        private void ConfigureModelAnnotations(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        }

        private void ConfigureClientEntity(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Client>(b =>
            {
                b.Property<int>(nameof(Client.Id))
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>(nameof(Client.Id)));

                b.Property<int>(nameof(Client.Cnpj))
                    .HasColumnType("int");

                b.Property<DateTime>(nameof(Client.DataCadastro))
                    .HasColumnType("datetime2");

                b.Property<string>(nameof(Client.NameClient))
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>(nameof(Client.RespClient))
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>(nameof(Client.TipoClient))
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey(nameof(Client.Id));

                b.ToTable("Client");
            });
        }
    }
}