// <auto-generated />
// NOTE: This is a refactored version of an EF Core model snapshot. The behavior and database mappings are preserved
// exactly as in the original generated snapshot. This file should remain a representation of the model used
// by EF migrations. Do not change mappings here unless you intend to change the database model.
//
// Developer guidance (non-functional comments):
// - Implement authentication (JWT or cookie-based) and role-based authorization in your Program.cs / Startup.cs
//   and controllers (use [Authorize] attributes and policies). Do not modify this snapshot for auth configuration.
// - Restrict CORS to trusted origins in production via configuration (avoid AllowAll in production). Keep dev/prod
//   configuration separate and secure.

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using client.Data;

#nullable disable

namespace backend.Migrations.Client
{
    [DbContext(typeof(ClientContext))]
    internal partial class ClientContextModelSnapshot : ModelSnapshot
    {
        private const string TableName = "Client";

        // Column type constants kept as strings to preserve exact DB column type mappings
        private const string ColumnTypeInt = "int";
        private const string ColumnTypeDateTime2 = "datetime2";
        private const string ColumnTypeNVarCharMax = "nvarchar(max)";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            if (modelBuilder == null) throw new ArgumentNullException(nameof(modelBuilder));

            ConfigureModelAnnotations(modelBuilder);
            ConfigureClientEntity(modelBuilder);
        }

        private void ConfigureModelAnnotations(ModelBuilder modelBuilder)
        {
            // Preserve EF Core annotations from the original snapshot
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // Ensure identity column usage for SQL Server as in the original snapshot
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        }

        private void ConfigureClientEntity(ModelBuilder modelBuilder)
        {
            // Configure the Client entity exactly as the original migration snapshot
            modelBuilder.Entity<Client>(ConfigureClient);

            void ConfigureClient(EntityTypeBuilder<Client> b)
            {
                ConfigureId(b);

                // Simple properties (preserve HasColumnType and nullability as in original)
                ConfigureProperty<int>(b, nameof(Client.Cnpj), ColumnTypeInt, isRequired: false);
                ConfigureProperty<DateTime>(b, nameof(Client.DataCadastro), ColumnTypeDateTime2, isRequired: false);

                // Required string properties
                ConfigureProperty<string>(b, nameof(Client.NameClient), ColumnTypeNVarCharMax, isRequired: true);
                ConfigureProperty<string>(b, nameof(Client.RespClient), ColumnTypeNVarCharMax, isRequired: true);
                ConfigureProperty<string>(b, nameof(Client.TipoClient), ColumnTypeNVarCharMax, isRequired: true);

                b.HasKey(nameof(Client.Id));

                b.ToTable(TableName);
            }
        }

        private static void ConfigureId(EntityTypeBuilder<Client> builder)
        {
            // Configure Id to match the original: int, identity column, value generated on add
            var idProperty = builder.Property<int>(nameof(Client.Id))
                .ValueGeneratedOnAdd()
                .HasColumnType(ColumnTypeInt);

            // Apply SQL Server identity column configuration as in the original snapshot
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(idProperty);
        }

        private static void ConfigureProperty<TEntityProperty>(EntityTypeBuilder<Client> builder, string propertyName, string columnType, bool isRequired)
        {
            var property = builder.Property<TEntityProperty>(propertyName)
                .HasColumnType(columnType);

            if (isRequired && typeof(TEntityProperty) == typeof(string))
            {
                // Preserve original .IsRequired() usage for string properties that were required
                property.IsRequired();
            }

            // Note: original snapshot only called IsRequired() for some string properties. For non-string
            // properties the original snapshot left default (nullable/non-nullable determined by CLR type).
        }
    }
}
