// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using user.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230811135034_atualiza")]
    partial class AtualizaMigration
    {
        private const string ProductVersion = "7.0.10";
        private const int MaxIdentifierLength = 128;
        private const string UsersTableName = "Users";

        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            ConfigureModel(modelBuilder);
#pragma warning restore 612, 618
        }

        /// <summary>
        /// Configures the model for this migration. Separated to aid readability and maintainability.
        /// NOTE: This is an auto-generated migration designer file — do not modify migration semantics.
        /// </summary>
        /// <param name="modelBuilder">Model builder instance provided by EF Core.</param>
        private void ConfigureModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", ProductVersion)
                .HasAnnotation("Relational:MaxIdentifierLength", MaxIdentifierLength);

            // Apply SQL Server identity column defaults (matches previous generated behavior)
            Microsoft.EntityFrameworkCore.SqlServer.Metadata.SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            ConfigureUserEntity(modelBuilder);
        }

        /// <summary>
        /// Configures the User entity mapping used by this migration.
        /// Kept as a separate method to make the model structure clearer.
        /// </summary>
        /// <param name="modelBuilder">Model builder instance.</param>
        private void ConfigureUserEntity(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(entity =>
            {
                // Shadow property "Id" configured as identity int.
                var idProperty = entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                // Ensure SQL Server identity column behavior is preserved.
                Microsoft.EntityFrameworkCore.SqlServer.Metadata.SqlServerPropertyBuilderExtensions.UseIdentityColumn(idProperty);

                // Required string properties for Login and Senha (password).
                entity.Property<string>("Login")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                entity.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                entity.HasKey("Id");

                entity.ToTable(UsersTableName);
            });
        }
    }
}
