// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using user.Data;

#nullable disable

namespace backend.Migrations
{
    /// <summary>
    /// Entity Framework Core model snapshot for <see cref="UserContext"/>.
    /// This file is auto-generated by EF Core migrations. Keep behavior identical to generated snapshot.
    /// NOTE: Do not manually modify model semantics that would change the database schema unless you intend to
    /// keep migrations and database in sync.
    /// </summary>
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        private const string ProductVersion = "7.0.10";
        private const int MaxIdentifierLength = 128;

        private const string TableUsers = "Users";
        private const string ColumnId = "Id";
        private const string ColumnLogin = "Login";
        private const string ColumnSenha = "Senha";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            if (modelBuilder == null) throw new ArgumentNullException(nameof(modelBuilder));

            ConfigureModelAnnotations(modelBuilder);
            ConfigureUserEntity(modelBuilder);
        }

        /// <summary>
        /// Configures model-level annotations (product version and SQL Server identity strategy).
        /// </summary>
        /// <param name="modelBuilder">The model builder instance.</param>
        private static void ConfigureModelAnnotations(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", ProductVersion)
                .HasAnnotation("Relational:MaxIdentifierLength", MaxIdentifierLength);

            // Configure SQL Server to use identity columns for key generation (matches generated snapshot behavior)
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        }

        /// <summary>
        /// Configures the Users entity (properties, keys and table mapping).
        /// </summary>
        /// <param name="modelBuilder">The model builder instance.</param>
        private static void ConfigureUserEntity(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(entity =>
            {
                // Id property
                var idProperty = entity.Property<int>(ColumnId);
                idProperty.ValueGeneratedOnAdd()
                          .HasColumnType("int");

                // Ensure SQL Server identity column is used exactly as in generated snapshot
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(idProperty);

                // Login property
                var loginProperty = entity.Property<string>(ColumnLogin);
                loginProperty.IsRequired()
                             .HasColumnType("nvarchar(max)");

                // Senha property
                var senhaProperty = entity.Property<string>(ColumnSenha);
                senhaProperty.IsRequired()
                             .HasColumnType("nvarchar(max)");

                entity.HasKey(ColumnId);
                entity.ToTable(TableUsers);
            });
        }
    }
}
