// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using avaliacao.Data;

#nullable disable

namespace backend.Migrations.Avaliacao
{
    [DbContext(typeof(AvaliacaoContext))]
    [Migration("20230812031323_atualiza")]
    partial class AtualizaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            ConfigureModel(modelBuilder);
        }

        private void ConfigureModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            ConfigureAvaliacaoEntity(modelBuilder);
        }

        private void ConfigureAvaliacaoEntity(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Avaliacao>(b =>
            {
                b.Property<int>(nameof(Avaliacao.Id))
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>(nameof(Avaliacao.Id)));

                b.Property<int>(nameof(Avaliacao.Client))
                    .HasColumnType("int");

                b.Property<DateTime>(nameof(Avaliacao.DataAvaliacao))
                    .HasColumnType("datetime2");

                b.Property<string>(nameof(Avaliacao.Motivo))
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>(nameof(Avaliacao.Nota))
                    .HasColumnType("int");

                b.HasKey(nameof(Avaliacao.Id));

                b.ToTable("Avaliacao");
            });
        }
    }
}