// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using avaliacao.Data;

#nullable disable

namespace backend.Migrations.Avaliacao
{
    [DbContext(typeof(AvaliacaoContext))]
    partial class AvaliacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            ConfigureModelBuilder(modelBuilder);
        }

        private static void ConfigureModelBuilder(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            ConfigureAvaliacaoEntity(modelBuilder);
            #pragma warning restore 612, 618
        }

        private static void ConfigureAvaliacaoEntity(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Avaliacao>(entity =>
            {
                entity.Property(e => e.Id)
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(entity.Property(e => e.Id));

                entity.Property(e => e.Client)
                    .HasColumnType("int");

                entity.Property(e => e.DataAvaliacao)
                    .HasColumnType("datetime2");

                entity.Property(e => e.Motivo)
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                entity.Property(e => e.Nota)
                    .HasColumnType("int");

                entity.HasKey(e => e.Id);

                entity.ToTable("Avaliacao");
            });
        }
    }
}