// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using avaliacao.Data;

#nullable disable

namespace backend.Migrations.Avaliacao
{
    /// <summary>
    /// Model snapshot for AvaliacaoContext. This file is a refactored version of the EF Core
    /// generated snapshot. Functionality is preserved. Configuration for authentication and CORS
    /// should be implemented in the application's Startup/Program (see TODO below).
    ///
    /// TODO:
    /// - Add authentication (JWT or cookie-based) and role-based authorization policies in the
    ///   application's Startup/Program and apply [Authorize] to controller endpoints.
    /// - Restrict CORS to known origins in production and separate dev/prod configuration. Do
    ///   NOT use AllowAll in production.
    ///
    /// This snapshot must remain data-model-only; runtime authentication/CORS belongs in the
    /// application configuration and controllers, not in EF migrations.
    /// </summary>
    [DbContext(typeof(AvaliacaoContext))]
    partial class AvaliacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            ConfigureModelBuilder(modelBuilder);
        }

        private static void ConfigureModelBuilder(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            ConfigureAvaliacaoEntity(modelBuilder);
            #pragma warning restore 612, 618
        }

        private static void ConfigureAvaliacaoEntity(ModelBuilder modelBuilder)
        {
            const string TableName = "Avaliacao";

            modelBuilder.Entity<Avaliacao>(entity =>
            {
                ConfigureAvaliacaoProperties(entity);

                entity.HasKey(e => e.Id);
                entity.ToTable(TableName);
            });
        }

        private static void ConfigureAvaliacaoProperties(EntityTypeBuilder<Avaliacao> entity)
        {
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(entity.Property(e => e.Id));

            entity.Property(e => e.Client)
                .HasColumnType("int");

            entity.Property(e => e.DataAvaliacao)
                .HasColumnType("datetime2");

            entity.Property(e => e.Motivo)
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            entity.Property(e => e.Nota)
                .HasColumnType("int");
        }
    }
}
